[package]
name = "pyu_rust_util"
version = "0.1.2"
edition = "2021"
description = "Utility functions for Rust."
license = "MIT"
authors = ["pyudev-x"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]